name: Terraform Azure Resource Group

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Environment Variables
        run: |
          echo "TF_VAR_client_id=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        
      - name: Initialize Terraform
        run: terraform init
      
      - name: Plan Terraform Changes
        run: |
          terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        
        # Ensure that the container has been created
        # This step assumes Azure CLI is already logged in
      - name: Check container existence
        run: |
            az storage container show --name tfstate --account-name dvstg991983 --auth-mode login
        
      - name: Generate backend configuration
        run: |
            cat <<EOF >backend.tf
            terraform {
              backend "azurerm" {
                resource_group_name   = "myrg"
                storage_account_name  = "dvstg991983"
                container_name        = "tfstate"
                key                   = "terraform.tfstate"
              }
            }
            EOF
        
      - name: Initialize Terraform with new backend
        run: terraform init -reconfigure
        

      - name: Commit backend configuration
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch
          git checkout ${{ github.ref }}
          git add backend.tf
          git commit -m "Add backend configuration"
          git push
        
