name: Terraform Azure Resource Group

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        
      - name: Initialize Terraform
        run: terraform init
      
      - name: Plan Terraform Changes
        run: |
          terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
      
      - name: Generate backend configuration
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "azurerm" {
              resource_group_name   = "myrg"
              storage_account_name  = "dvstg991983"
              container_name        = "tfstate"
              key                   = "terraform.tfstate"
            }
          }
          EOF
      

  # Migrate state to the new backend
      - name: Migrate Terraform state to the Azure backend
        run: |
          terraform init -migrate-state

      - name: Commit backend configuration
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch
          git checkout ${{ github.ref }}
          git add backend.tf
          git commit -m "Add backend configuration"
          git push
        
